"""学校讨论平台: 新增板块/点赞/收藏/通知, 评论支持楼中楼

Revision ID: 00be4481da2e
Revises: 089a3d563c10
Create Date: 2026-06-13 11:08:47.400592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00be4481da2e'
down_revision: Union[str, Sequence[str], None] = '089a3d563c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='板块id'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='板块名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='板块描述'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='板块图标'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序权重'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='收藏id'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='帖子id'),
    sa.Column('user_uid', sa.String(length=36), nullable=False, comment='收藏用户uid'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_uid', name='uq_user_post_bookmark')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='点赞id'),
    sa.Column('post_id', sa.Integer(), nullable=False, comment='帖子id'),
    sa.Column('user_uid', sa.String(length=36), nullable=False, comment='点赞用户uid'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_uid', name='uq_user_post_like')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='通知id'),
    sa.Column('recipient_uid', sa.String(length=36), nullable=False, comment='接收者uid'),
    sa.Column('sender_uid', sa.String(length=36), nullable=True, comment='触发者uid（系统通知可为空）'),
    sa.Column('notif_type', sa.String(length=50), nullable=False, comment='通知类型: reply / like / system'),
    sa.Column('post_id', sa.Integer(), nullable=True, comment='相关帖子id'),
    sa.Column('content', sa.Text(), nullable=True, comment='通知内容'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_time', sa.DateTime(), nullable=True, comment='阅读时间'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_uid'], ['user.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_uid'], ['user.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论id（支持楼中楼）'))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['id'], ondelete='CASCADE')
    op.add_column('posts', sa.Column('is_top', sa.Boolean(), nullable=False, comment='是否置顶'))
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True, comment='板块id'))
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('user_id'), table_name='token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('user_id'), 'token', ['user_uid'], unique=False)
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    op.drop_column('posts', 'is_top')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    op.drop_table('notifications')
    op.drop_table('likes')
    op.drop_table('bookmarks')
    op.drop_table('categories')
    # ### end Alembic commands ###
