"""加长refresh_token

Revision ID: 089a3d563c10
Revises: 2284c38dee2f
Create Date: 2026-05-04 20:20:52.236107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '089a3d563c10'
down_revision: Union[str, Sequence[str], None] = '2284c38dee2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'refresh_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=512),
               existing_comment='刷新令牌',
               existing_nullable=False)
    op.drop_index(op.f('user_id'), table_name='token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('user_id'), 'token', ['user_uid'], unique=False)
    op.alter_column('token', 'refresh_token',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_comment='刷新令牌',
               existing_nullable=False)
    # ### end Alembic commands ###
