"""新增token表，更新关联表

Revision ID: 2284c38dee2f
Revises: ba81d79c0748
Create Date: 2026-05-03 20:14:56.134330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2284c38dee2f'
down_revision: Union[str, Sequence[str], None] = 'ba81d79c0748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'user', ['author_uid'], ['uid'], onupdate='CASCADE')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint(op.f('posts_ibfk_1'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'user', ['author_uid'], ['uid'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_ibfk_1'), 'posts', 'user', ['author_uid'], ['uid'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
