"""移除用户头像

Revision ID: 5e892e7a9720
Revises: 00be4481da2e
Create Date: 2026-06-15 19:29:10.785624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e892e7a9720'
down_revision: Union[str, Sequence[str], None] = '00be4481da2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_id'), table_name='token')
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='头像'))
    op.create_index(op.f('user_id'), 'token', ['user_uid'], unique=False)
    # ### end Alembic commands ###
