"""Alembic测试

Revision ID: 708180b8e30c
Revises: 
Create Date: 2026-04-28 20:31:36.999571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '708180b8e30c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=mysql.ENUM('男', '女', '未知', collation='utf8mb4_unicode_ci'),
               nullable=False,
               existing_comment='性别')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'gender',
               existing_type=mysql.ENUM('男', '女', '未知', collation='utf8mb4_unicode_ci'),
               nullable=True,
               existing_comment='性别')
    # ### end Alembic commands ###
